application: portfolio-kunika
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /img
  static_dir: img



- url: /*
  static_files: index.html
  upload: index.html

- url: /index.*
  static_files: index.html
  upload: index.html

- url: /contact.*
  static_files: contact.html
  upload: contact.html

- url: /about.*
  static_files: about.html
  upload: about.html
